### ISSUE TITLE
Change first module name to something other than package name

### ISSUE THREAD

**Issue by Lnaden** [choderalab/cookiecutter-python-comp-chem#8]
Suggestion by @bas-rustenburg 

> the package and first submodule would have the same name. I wonder if that could be a confusing start of a package.

Also a suggestion from @jchodera 

> I’d choose whimsical package and submodule names

Personally: I’d like to avoid just using whimsical names, the whole point of the cookiecutter is to have it fill in things. I could add another option on init to set the first module name, defaulting to the package name.

**Comment by jchodera** [comment]
Ah! Good point. Sorry for having missed that.
